name: iOS Preview Build (Develop)

on:
  push:
    branches: ["develop"]
    paths:
      - "apps/mobile/**"
      - "packages/**"

jobs:
  build_ios_preview:
    name: Build iOS preview
    type: build
    params:
      platform: ios
      profile: preview